package com.pos;
import javax.swing.*; import java.awt.*; import java.sql.*;
public class AccountManagementPanel extends JPanel { private final UserSession s; private final QueryTableModel model=new QueryTableModel(); private final JTable table=new JTable(model); private final JTextField username=new JTextField(14), fullname=new JTextField(18),email=new JTextField(18),phone=new JTextField(13),password=new JTextField(13); private final JComboBox<String> role=new JComboBox<String>(new String[]{"ADMIN","CASHIER","CUSTOMER"});
 public AccountManagementPanel(UserSession s){super(new BorderLayout(10,10));this.s=s;JPanel h=new JPanel(new BorderLayout());h.add(UIUtils.title("Account Management"),BorderLayout.WEST);JButton refresh=new JButton("Refresh");h.add(refresh,BorderLayout.EAST);add(h,BorderLayout.NORTH);add(new JScrollPane(table),BorderLayout.CENTER);JPanel form=new JPanel(new GridLayout(0,2,5,5));form.setBorder(BorderFactory.createTitledBorder("New Account / Selected Actions"));form.add(new JLabel("Username"));form.add(username);form.add(new JLabel("Full Name"));form.add(fullname);form.add(new JLabel("Email"));form.add(email);form.add(new JLabel("Phone"));form.add(phone);form.add(new JLabel("Password"));form.add(password);form.add(new JLabel("Role"));form.add(role);JButton add=new JButton("Create Account"),active=new JButton("Activate"),inactive=new JButton("Deactivate"),reset=new JButton("Reset Password");form.add(add);form.add(active);form.add(inactive);form.add(reset);add(form,BorderLayout.EAST);refresh.addActionListener(e->load());add.addActionListener(e->create());active.addActionListener(e->status("ACTIVE"));inactive.addActionListener(e->status("INACTIVE"));reset.addActionListener(e->reset());load();}
 private int selected(){int r=table.getSelectedRow();return r<0?0:Integer.parseInt(String.valueOf(table.getValueAt(table.convertRowIndexToModel(r),0)));}
 private void load(){try{model.load("SELECT user_id,username,full_name,email,phone,role,status,created_at FROM users ORDER BY user_id DESC");table.setAutoCreateRowSorter(true);}catch(Exception e){UIUtils.error(this,e);}}
 private void create(){try(Connection c=DB.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO users(username,password_hash,full_name,email,phone,role,status) VALUES(?,?,?,?,?,?, 'ACTIVE')")){if(username.getText().trim().isEmpty()||password.getText().length()<6)throw new SQLException("Username and password of at least 6 characters are required.");p.setString(1,username.getText().trim());p.setString(2,PasswordUtil.hash(password.getText()));p.setString(3,fullname.getText().trim());p.setString(4,email.getText().trim());p.setString(5,phone.getText().trim());p.setString(6,String.valueOf(role.getSelectedItem()));p.executeUpdate();Audit.log(s,"CREATE_ACCOUNT",username.getText());load();UIUtils.info(this,"Account created.");}catch(Exception e){UIUtils.error(this,e);}}
 private void status(String value){int id=selected();if(id==0)return;if(id==s.userId&&"INACTIVE".equals(value)){UIUtils.info(this,"You cannot deactivate your current login.");return;}try(Connection c=DB.getConnection();PreparedStatement p=c.prepareStatement("UPDATE users SET status=? WHERE user_id=?")){p.setString(1,value);p.setInt(2,id);p.executeUpdate();Audit.log(s,"ACCOUNT_STATUS",id+"="+value);load();}catch(Exception e){UIUtils.error(this,e);}}
 private void reset(){int id=selected();if(id==0||password.getText().length()<6){UIUtils.info(this,"Select an account and enter a new password of at least 6 characters.");return;}try(Connection c=DB.getConnection();PreparedStatement p=c.prepareStatement("UPDATE users SET password_hash=? WHERE user_id=?")){p.setString(1,PasswordUtil.hash(password.getText()));p.setInt(2,id);p.executeUpdate();Audit.log(s,"RESET_PASSWORD","user_id="+id);UIUtils.info(this,"Password reset.");}catch(Exception e){UIUtils.error(this,e);}}
}
