package com.pos;
import javax.swing.*; import java.awt.*; import java.sql.*; import java.util.*;
public class CrudPanel extends JPanel { private final CrudConfig cfg; private final UserSession session; private final QueryTableModel model=new QueryTableModel(); private final JTable table=new JTable(model); private final JTextField id=new JTextField(8), search=new JTextField(18); private final Map<String,JTextField> fields=new LinkedHashMap<String,JTextField>();
 public CrudPanel(CrudConfig c,UserSession s){ super(new BorderLayout(8,8)); cfg=c;session=s; build();refresh(); }
 private void build(){ JPanel h=new JPanel(new BorderLayout()); h.add(UIUtils.title(cfg.title),BorderLayout.WEST); JPanel q=new JPanel(); q.add(new JLabel("Search:"));q.add(search); JButton go=new JButton("Search"),all=new JButton("Refresh"),ex=new JButton("Export CSV");q.add(go);q.add(all);q.add(ex);h.add(q,BorderLayout.EAST);add(h,BorderLayout.NORTH); table.setAutoCreateRowSorter(true); add(new JScrollPane(table),BorderLayout.CENTER);
  JPanel f=new JPanel(new GridBagLayout()); f.setBorder(BorderFactory.createTitledBorder("Record Form")); GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(3,3,3,3);g.fill=GridBagConstraints.HORIZONTAL;int r=0; id.setEditable(false); g.gridx=0;g.gridy=r;f.add(new JLabel(cfg.idColumn),g);g.gridx=1;f.add(id,g);r++; for(String x:cfg.fields){JTextField tf=new JTextField(17);fields.put(x,tf);g.gridx=0;g.gridy=r;f.add(new JLabel(x),g);g.gridx=1;f.add(tf,g);r++;} JPanel b=new JPanel(); JButton nw=new JButton("New"),add=new JButton("Add"),upd=new JButton("Update"),del=new JButton("Delete");b.add(nw);b.add(add);b.add(upd);b.add(del);g.gridx=0;g.gridy=r;g.gridwidth=2;f.add(b,g);add(new JScrollPane(f),BorderLayout.EAST);
  all.addActionListener(e->refresh());go.addActionListener(e->doSearch());search.addActionListener(e->doSearch());ex.addActionListener(e->CsvExporter.exportTable(this,table,cfg.title.replace(' ','_')+".csv"));nw.addActionListener(e->clear());add.addActionListener(e->insert());upd.addActionListener(e->update());del.addActionListener(e->delete());table.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting()) select();}); }
 private void refresh(){ try{model.load(cfg.selectSql);}catch(Exception e){UIUtils.error(this,e);} } private void doSearch(){try{ if(search.getText().trim().isEmpty()){refresh();return;} model.load(cfg.selectSql+" WHERE CAST("+cfg.searchColumn+" AS CHAR) LIKE ?","%"+search.getText().trim()+"%"); }catch(Exception e){UIUtils.error(this,e);} }
 private void clear(){id.setText("");for(JTextField f:fields.values())f.setText("");table.clearSelection();} private Object v(String x){String s=fields.get(x).getText().trim();return s.isEmpty()?null:s;}
 private void select(){int r=table.getSelectedRow();if(r<0)return;r=table.convertRowIndexToModel(r);int p=model.findColumnByName(cfg.idColumn);if(p>=0)id.setText(String.valueOf(model.getValueAt(r,p)));for(String f:cfg.fields){p=model.findColumnByName(f);if(p>=0)fields.get(f).setText(model.getValueAt(r,p)==null?"":String.valueOf(model.getValueAt(r,p)));}}
 private void insert(){String s="INSERT INTO "+cfg.table+"("+Sql.csvList(cfg.fields)+") VALUES("+Sql.placeholders(cfg.fields.length)+")";try(Connection c=DB.getConnection();PreparedStatement p=c.prepareStatement(s)){for(int i=0;i<cfg.fields.length;i++)p.setObject(i+1,v(cfg.fields[i]));p.executeUpdate();Audit.log(session,"ADD_"+cfg.table,"New record");refresh();clear();UIUtils.info(this,"Record added.");}catch(Exception e){UIUtils.error(this,e);}}
 private void update(){if(id.getText().isEmpty()){UIUtils.info(this,"Select a record first.");return;}String s="UPDATE "+cfg.table+" SET "+Sql.assignmentList(cfg.fields)+" WHERE "+cfg.idColumn+"=?";try(Connection c=DB.getConnection();PreparedStatement p=c.prepareStatement(s)){for(int i=0;i<cfg.fields.length;i++)p.setObject(i+1,v(cfg.fields[i]));p.setString(cfg.fields.length+1,id.getText());p.executeUpdate();Audit.log(session,"UPDATE_"+cfg.table,cfg.idColumn+"="+id.getText());refresh();UIUtils.info(this,"Record updated.");}catch(Exception e){UIUtils.error(this,e);}}
 private void delete(){if(id.getText().isEmpty()||!UIUtils.confirm(this,"Delete selected record?"))return;try(Connection c=DB.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM "+cfg.table+" WHERE "+cfg.idColumn+"=?")){p.setString(1,id.getText());p.executeUpdate();Audit.log(session,"DELETE_"+cfg.table,cfg.idColumn+"="+id.getText());refresh();clear();}catch(Exception e){UIUtils.error(this,e);}}
}
